<a href="https://colab.research.google.com/github/tabssum/Python_to_AI_Learning_Journey/blob/main/numpy_exercise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Exercise 1: Create a 1D NumPy array of numbers from 0 to 9**

In [1]:
import numpy as np

array=np.arange(0,10)
print(array)

[0 1 2 3 4 5 6 7 8 9]


**Exercise 2: Write a code to convert a 1D array to a 2D array with 2 rows.**

In [3]:
nd_array=np.reshape(array,(2,5))
print(nd_array)

[[0 1 2 3 4]
 [5 6 7 8 9]]


Exercise 3: Print Array Attributes Instructions: Print the following attributes of the array:

The shape of the array.
The number of array dimensions.
The size of each element in bytes

In [4]:
#Shape of the array

print(nd_array.shape)

#Dimensions of the array
print(nd_array.ndim)

#Size of the array
print(nd_array.size)

(2, 5)
2
10


**Exercise 4: Create a 3×3 NumPy array of all True**